- name: Replace /etc/motd file
  hosts: all
  become: true
  become_user: root
  tasks:
     - name: Update /etc/motd on proxy host group
       copy:
         content: 'Welcome to HAProxy server'
         dest: /etc/motd
       when: ansible_fqdn in groups['proxy'] 

     - name: Update /etc/motd on webservers host group
       copy:
         content: 'Welcome to Apache server'
         dest: /etc/motd
       when: ansible_fqdn in groups['webservers'] 

     - name: Update /etc/motd on database host group
       copy:
         content: 'Welcome to HAProxy server'
         dest: /etc/motd
       when: ansible_fqdn in groups['database'] 
