- name: mysql main playbook
  hosts: database
  become: true
  become_user: root
  vars_files: secret.yml
  gather_facts: yes
  pre_tasks:
       - command: /usr/bin/yum module disable mysql -y
  roles: 
    - sample-mysql
