- name: Install packages
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install packages on proxy group
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - tcpdump
        - mailx
      when: ansible_fqdn in groups['proxy']

    - name: Install packages on database group
      yum:
        name: "{{ item }}"
        state: present
      loop:
       - lsof
       - mailx
      when: ansible_fqdn in groups['database']
