- name: Create a repo
  hosts: database
  become: true
  become_user: root
  tasks:
    - name: Create a repository file
      yum_repository:
        name: mysql56-community
        description: MySQL 5.6 YUM Repo
        baseurl: http://repo.mysql.com/yum/mysql-5.6-community/el/7/x86_64/
        gpgcheck: true
        gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
        enabled: true
