- name: Selinux configuration
  hosts: webservers
  become: true
  become_user: root
  tasks:
     - name: Set the default target to multi-user
       file:
         src: /lib/systemd/system/multi-user.target
         dest: /etc/systemd/system/default.target
         state: link
