- name: Create a custom facts file
  hosts: database
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: Create a custom facts directory
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: Create a custom facts
      template:
        src: templates/custom.fact.j2
        dest: /etc/ansible/facts.d/custom.fact

    - name: Print ansible_local
      debug: var=ansible_local
    - name: Print the custom facts value
      debug:
        msg: "{{ ansible_local.custom.sample_exam }}"
