---
- name: Configure HAProxy
  hosts: webservers
  become: true
  become_user: root
  gather_facts: yes
  vars:
    haproxy_backend_balance_method: 'roundrobin'
    haproxy_backend_servers:
      - name: web1
        address: ansible3.example.com:80
      - name: web2
        address: ansible4.example.com:80

  pre_tasks:
    - debug:
        msg: "Beginning to configure HAProxy"

  tasks:
    - name: Install HAProxy
      import_role:
         name: geerlingguy.haproxy

    - name: Configure firewall to allow traffic
      firewalld:
         service: http
         state: enabled
         permanent: yes
      notify: reload firewalld

  handlers:
    - name: reload firewalld
      service:
         name: firewalld
         state: reloaded
      listen: reeload firewalld

  post_tasks:
     - debug: 
         msg: "HAProxy configuration completed"
