- name: Configure SELINUX
  hosts: webservers
  become: true
  become_user: root
  vars:
    selinux_policy: targeted
    selinux_state: enforcing
  tasks:
    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
      seboolean:
         name: httpd_can_network_connect
         state: yes
         persistent: yes
  roles:
    - linux-system-roles.selinux
