- name: Configure SSH
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Set Banner to /etc/motd
      lineinfile:
          path: /etc/ssh/sshd_config
          regex: '^#Banner'
          line: Banner /etc/motd

    - name: Set X11Forwarding
      lineinfile:
          path: /etc/ssh/sshd_config
          regex: '^X11Forwarding'
          line: X11Forwarding no

    - name: Set MaxAuthTries
      lineinfile:
          path: /etc/ssh/sshd_config
          regex: '^#MaxAuthTries'
          line: MaxAuthTries 3
