- name: Configure sysctl
  hosts: all
  become: true
  become_user: root
  gather_facts: yes
  tasks:
    - name: Configure vm.swappiness
      command: /usr/sbin/sysctl vm.swappiness=10
      when: ansible_memory_mb['real']['total'] > 2048

    - name: Display error message
      fail:
        msg: Server memory less than 2048MB
      when: ansible_memory_mb['real']['total'] < 2048
